### ISSUE TITLE
consider bump version for newer tower-web

### ISSUE THREAD

**Issue by davyzhang** [robertgzr/juniper_tower#1]
They move RootNode to root 😄 

`type Schema = juniper::RootNode<'static, Query, Mutation>;`

other than

`type Schema = juniper::schema::model::RootNode<'static, Query, Mutation>;`

here's the Cargo.toml

```
tower-web = "0.3.7"
futures = "0.1"

http = "0.1.17"
serde = "1.0.93"
serde_json = "1.0.39"
tokio = "0.1.21"
```

**Comment by robertgzr** [comment]
> They move RootNode to root :smile:
>
> `type Schema = juniper::RootNode<'static, Query, Mutation>;`
> 
> other than
> 
> `type Schema = juniper::schema::model::RootNode<'static, Query, Mutation>;`

not sure what you mean by that, we're using it like that since the very first commit https://github.com/robertgzr/juniper_tower/blob/master/src/lib.rs#L8

And I bumped the juniper and tower-web versions in [v0.2.0](https://github.com/robertgzr/juniper_tower/releases/tag/0.2.0)

**Comment by davyzhang** [comment]
Oops, looks Iike my IDE gives me wrong error information. sorry.
